<div class="wrapperFooterPageStatic">
<div id="AboutUsContent">



<div id="AboutUsMainImg"><img style="float: left; margin-right: 20px;" src="http://d2zmgde9txxwg2.cloudfront.net/images/about/AboutUs_LargeImage.jpg" alt="" /></div>


<h2>THE FUTURE OF MOBILITY</h2>
<div class="aboutRow">
	<img class="left icon" src="http://d2zmgde9txxwg2.cloudfront.net/images/about/abouti1.png" alt="" />
	<p style="margin-left: 110px; margin-top: 20px;">Incipio<span class="super">&reg;</span> began in 1999 with the goal of making a case that would protect your mobile device. Over the last 15 years we have grown to an award-winning global designer and manufacturer of mobile device accessories and technologies that are sold in over 40,000 retail locations worldwide.</p>
</div>

<br /> 

<div class="aboutRow">
	<img class="left icon" src="http://d2zmgde9txxwg2.cloudfront.net/images/about/abouti2.png" alt="" />
	<p style="margin-left: 110px;">As the industry evolves, Incipio<span class="super">&reg;</span> is continually at the forefront of mobile technology. Incorporating technologies like Bluetooth<span class="super">&reg;</span> low energy, wireless charging, NFC, and mobile apps, we are a company that integrates technology in innovative, undiscovered ways. Through our strategic partnerships and handset programs, we offer products at the time of device launch, providing consumers the accessories they need the moment their device is activated.</p>
</div>

<br />

<div class="aboutRow">
	<img class="left icon" src="http://d2zmgde9txxwg2.cloudfront.net/images/about/abouti3.png" alt="" />
	<p style="margin-left: 110px; margin-bottom: 10px;">We take pride in being constantly on the brink of innovation; and joining with Braven in 2013 has allowed us to widen our presence and step into the world of high fidelity, wireless audio speakers. Incipio has aided in Braven’s expansion by helping conceptualize and build award-winning waterproof rugged speakers, Smart battery banks, and interactive wireless home audio systems.</p>
</div>

<br />

<div class="aboutRow">
	<img class="left icon" src="http://d2zmgde9txxwg2.cloudfront.net/images/about/abouti4.png" alt="" />
	<p style="margin-left: 110px; margin-bottom: 10px;">With the scope of Incipio® ever-growing, we have gone from a one-man shop to expansive headquarters in Southern California, with additional offices in San Francisco, Seattle, Salt Lake City, Minneapolis, London, Hong Kong, India and Italy. This growth is just the beginning, as our talented team of over 350 employees continues to push the bounds of mobility.</p>
</div>

<div class="right bottomImg aboutRow">
	<img src="http://d2zmgde9txxwg2.cloudfront.net/images/about/AboutUs_bottom1.png" alt="" class="left"/>
	<img src="http://d2zmgde9txxwg2.cloudfront.net/images/about/AboutUs_bottom2.png" alt="" class="left lastImg"/>
</div>

</div>
</div>


<style>


.bottomImg img{
	width: 50%;
}
.aboutRow {
	display: table;
	margin-bottom: 10px;
	height: 100px; 
	float: right;
	width: 53%;
	clear: right;
}
.bottomImg{
	margin: 0;
	top: 5px;
	position: relative;
}

.lastImg {
	left: 20px;
	position: relative;
}
.cms-page-view .std p, .cms-no-route .std p {
    color: #636363;
    font-family: "Roboto Condensed",arial,sans-serif;
    font-size: 14px;
    line-height: 17px;
}
.main-container, .footer-container { 
    padding-bottom: 40px;
}

h2 {
	font-size: 28px; font-weight: bold; color:black; left:130px; position:relative;
}
@media (max-width: 990px) {
	#AboutUsMainImg {
		display: none;
	}
	.aboutRow {
		width:100%;
		float: left;
	}
	h2 {
		text-align: center;
		left: 0!important;
		color:black!important;
	}
	.cms-page-view .std h2, .cms-no-route .std h2 {

		color:black!important;
	}


	#AboutUsContent p{
		text-align: center;
		left: 0;
		margin: 0!important;
	}

	#AboutUsContent .icon{
		margin: 0 auto;
		display:block;
		float:none!important;
	}

	.bottomImg img {
	    width: 48%;
	}



}
</style>