 

 <img src="http://www.incipio.com/images/blackFriday/Black_Friday_Webpage_01.jpg">
 <div id="textOverlay">
	 <h3>BLACK FRIDAY SAVINGS </h3>
	 <h3> ARE RIGHT AROUND THE CORNER</h3> 
	<ul>
	   <li><a href="https://www.facebook.com/incipio" target="_blank"><i class="fa fa-facebook"></i></a></li>
	   <li><a href="https://twitter.com/myincipio" target="_blank"><i class="fa fa-twitter"></i></a></li>
	   <li><a href="http://www.youtube.com/user/IncipioTV" target="_blank"><i class="fa fa-youtube"></i></a></li>
	   <li><a href="http://www.pinterest.com/incipio/" target="_blank"><i class="fa fa-pinterest"></i></a></li>
	   <li><a href="http://instagram.com/incipio#" target="_blank"><i class="fa fa-instagram"></i></a></li>
	</ul>
 </div>


 </div>
 <ul id="xmasOrbs">
	 <li><img src="http://www.incipio.com/images/blackFriday/ENTER_INFO.png"></li>
	 <li><img src="http://www.incipio.com/images/blackFriday/SELECT.png" ></li>
	 <li><img src="http://www.incipio.com/images/blackFriday/VIP.png"></li>
 </ul>
 

<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{  clear:left; font:15px Helvetica,Arial,sans-serif; }
	label {
		font-size: 15px;
		font-weight: normal;
		text-transform: uppercase;
	}
	#mc_embed_signup .button {
		font-weight:normal !important;
	}
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
	.main-container {
	   background-image:url('http://www.incipio.com/images/blackFriday/Black_Friday_Webpage_02.jpg');

	}

	#mc_embed_signup form {
		padding: 0!important;
	}
	#mc_embed_signup .mc-field-group {
		width: 100%!important;
	}	'
	#xmasOrbs ul {
		top: 11px;
		position: relative;
	}
	#xmasOrbs li {
		width:33.3333%;
		list-style: none;
		float: left;
	}
	#xmasOrbs li img {
		display: block;
		margin: 0 auto;
	}
	#xmasOrbs li img {
	    display: block;
	    margin: 0px auto;
	    max-width: 177px;
	    width: 100%;
	}
	#xmasOrbs {
		background: none repeat scroll 0% 0% #740013;
		width: 100%;
		height: 100;
		display: table;
		margin-top: -24px;
		padding: 20px 0px;
	}
	#textOverlay {
		position: absolute;
		top:70%;
		left:40px;
		padding: 20px;
	}
	#textOverlay ul{ 
		position: relative;
		top:15px;

	}
	#textOverlay li{
		list-style: none;
		float: left;
		color: white!important;
	}

	#textOverlay li a{ 
		color: white!important;
		padding-right: 10px;
	}

	#textOverlay h3 { 
		font-weight: 600px!important;
		color: white!important;
		line-height: 1!important;
	}
	.std {
		position: relative;
	}
	form {
		margin: 40px 0 20px 0;
	}
	h3 {
		margin:0!important;
		font-weight: 600!important;
	}
 
	@media screen and (max-width: 830px) {
		#textOverlay {
			position: relative;
			width:100%;
			background: black;
			left:0;
			top:0;

		}
		.std p {
		    margin: 0px 0px 0!important;
		}
		#textOverlay ul {
			display: none;
		}
		#xmasOrbs li { 
		    position: relative!important;
		    top: 10px!important;
		} 
	}
 	@media screen and (max-width: 830px) {
 		.col1-layout .col-main {
 			position: relative;
		    top: 40px;
		}
 	}
</style>
<div id="mc_embed_signup">
<form action="//incipio.us2.list-manage.com/subscribe/post?u=69b6f0214b67470e06547aeb0&amp;id=103aa41e1f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<div class="mc-field-group">
		<label for="mce-MMERGE1">First Name </label>
		<input type="text" value="" name="MMERGE1" class="" id="mce-MMERGE1">
	</div>
	<div class="mc-field-group">
		<label for="mce-LNAME">Last Name </label>
		<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
	</div>
	<div class="mc-field-group">
		<label for="mce-EMAIL">Email Address</label>
		<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
	</div>
<div class="mc-field-group input-group">
   <h3>Select the devices you want to learn more about </h3>
    <ul>
<li><input type="checkbox" value="1024" name="group[2897][1024]" id="mce-group[2897]-2897-5"><label style="padding-left:6px;" for="mce-group[2897]-2897-5">iPhone Cases</label></li>
<li><input type="checkbox" value="2048" name="group[2897][2048]" id="mce-group[2897]-2897-6"><label style="padding-left:6px;" for="mce-group[2897]-2897-6">iPad Cases</label></li>
<li><input type="checkbox" value="4096" name="group[2897][4096]" id="mce-group[2897]-2897-7"><label style="padding-left:6px;" for="mce-group[2897]-2897-7">Samsung Smartphone Cases</label></li>
<li><input type="checkbox" value="8192" name="group[2897][8192]" id="mce-group[2897]-2897-8"><label style="padding-left:6px;" for="mce-group[2897]-2897-8">Chargers / Backup Batteries</label></li>
<li><input type="checkbox" value="16384" name="group[2897][16384]" id="mce-group[2897]-2897-9"><label style="padding-left:6px;" for="mce-group[2897]-2897-9">Backpacks / Sleeves</label></li>
<li><input type="checkbox" value="32768" name="group[2897][32768]" id="mce-group[2897]-2897-10"><label style="padding-left:6px;" for="mce-group[2897]-2897-10">Bluetooth Speakers</label></li>
<li><input type="checkbox" value="65536" name="group[2897][65536]" id="mce-group[2897]-2897-11"><label style="padding-left:6px;" for="mce-group[2897]-2897-11">Earbuds / Headphones</label></li>
</ul>
</div>
<div class="mc-field-group input-group">
    <h3> Email Format </h3>
    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label style="padding-left:6px;" for="mce-EMAILTYPE-0">html</label></li>
<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label style="padding-left:6px;" for="mce-EMAILTYPE-1">text</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_69b6f0214b67470e06547aeb0_103aa41e1f" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->








<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="http://www.incipio.com/skin/frontend/rwd/default/js/jquery.fittext.js"></script>
<script type="text/javascript">  
	$("#textOverlay h3").fitText(2, { minFontSize: '20px', maxFontSize: '50px' }); 
</script>
