 
  <section id="incipio_enterprise"></section>
  <section id="business_solutions">
  	<h2>BUSINESS SOLUTIONS FOR A BETTER FUTURE</h2>
    <p class="titleP" >Incipio&reg; provides high-quality mobile solutions that protect and integrate with your business.  As a technology partner, Incipio&reg; will provide you with innovative, reliable business solutions to ensure your organization will thrive.</p>
  </section>
  <section id="enterprise_lifestyle">  </section>
  <section id="enterprise_solutions">
  	<h2>LEADING TECHNOLOGY PROVIDER </h2>
    <p class="titleP">Whether you're a growing business, a governing body, a healthcare network or an educator, Incipio&reg; is prepared to provide unique solutions tailored to your industry with your success in mind.</dip>
    <ul>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i1.png">
    		</div>
    		<div class="right">
    			<h5>COMMERCIAL</h5> 
    			<p>TECHNOLOGY THAT DRIVES YOUR  BUSINESS AND BOOSTS PRODUCTIVITY  AND IMPROVES EFFICIENCY.</p>
    		</div>
    	</li>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i4.png">
    		</div>
    		<div class="right">
    			<h5>EDUCATION</h5> 
    			<p>OUTFITTING THE 21ST CENTURY CLASSROOM WITH THE MOBILE INNOVATIONS EDUCATORS AND STUDENTS NEED TO THRIVE.</p>
    		</div>
    	</li>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i2.png">
    		</div>
    		<div class="right">
    			<h5>FINANCE</h5> 
    			<p> WE UNDERSTAND THE UNIQUE NEEDS OF YOUR INDUSTRY AND THE NEED FOR COMPLETE MOBILE PROTECTION.</p>
    		</div>
    	</li>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i5.png">
    		</div>
    		<div class="right">
    			<h5>GOVERNMENT</h5> 
    			<p> HIGH-GRADE, ULTRA-RELIABLE SOLUTIONS FOR LOCAL AND FEDERAL GOVERNMENTS.</p>
    		</div>
    	</li>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i3.png">
    		</div>
    		<div class="right">
    			<h5>HEALTHCARE</h5> 
    			<p> INNOVATIVE, RELIABLE PRODUCTS FOR THE HEALTHCARE INDUSTRY.</p>
    		</div>
    	</li>
    	<li>
    		<div class="left">
    			<img src="http://www.incipio.com/images/enterprise/i6.png">
    		</div>
    		<div class="right">
    			<h5>RETAIL </h5>
    			<p> ENHANCE YOUR SUCCESS WITH INCIPIO'S POINT OF PURCHASE AND  POINT OF SALE RETAIL SOLUTIONS.</p>
    		</div>
    	</li>
     	

    </ul>
   		
  </section>
  <section id="enterprise_lifestyle2"></section>
  <section id="solutions_focused">
  	<h2>SOLUTIONS FOCUSED</h2>
    <p class="titleP">Incipio works with all major mobile manufacturers to provide integrated solutions across multiple segments.</dip>
     <ul>
   	    <li><img src="http://www.incipio.com/images/enterprise/s1.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s2.png"></li>   
   	    <li><img src="http://www.incipio.com/images/enterprise/s3.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s4.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s5.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s6.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s7.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s8.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s9.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s10.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s11.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s12.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s13.png"></li> 
   	    <li><img src="http://www.incipio.com/images/enterprise/s14.png"></li>  
   	</ul>


  </section>
  <section id="enterprise_warehouse"></section>
  <section id="enterprise_form">
  	<h2>BECOME A PARTNER </h2>
    <p class="titleP">Incipio&reg; is here to provide mobile solutions for the success of your business.</p>
    <p><span>CONTACT US : Please send us your info and we will follow up with you directly.</p>

	<!-- Start code for the form-->
	<style>
	.error{color:red !important;font-size: 12px !important;clear: both;float: right;}
	.message{margin-top:0px !important;}
	#formtable{border: 0px none !important;border-spacing:10px !important;}
	#enterprise_form_container{width:100% !important;}
	</style>
	<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
	<script>
	jQuery(document).ready(function(){
		jQuery("#myemailform").validate({
	  	rules: {
		    name: {
		     	required: true
		    },
			  company: {
			    required: true
		    },
		    email: {
		     required: true,
		    },
	      phone: {
	      	required: true
	      }
	    },
	    	messages: {
	      	name: {
	        	required:"Please enter your name"
	        },
	        company: {
	          required: "Please enter your company name",
	        },
	        email: {
				required: "Please enter a valid email address",
			},	
	        phone: {
	         required: "Please enter your phone number",
	        }
	      },
	      submitHandler: function(form)
	      {
	      	var name_val = jQuery("#name").val();
	        var company_val = jQuery("#company").val();
	        var email_val = jQuery("#email").val();
	        var phone_val = jQuery("#phone").val();
	        var message_val = jQuery("#message").val();
	        var dataString = 'name='+ name_val + '&company='+ company_val+ '&email='+ email_val+ '&phone='+ phone_val+ '&message='+ message_val;
	        jQuery.ajax({
		        type: "POST",
		        url: "form-to-email.php",
		        data: dataString,
		        cache: false,
		        //success: function(html){
		        	
		        		//$("#myemailform")[0].reset();
		                                                         			
		        		//$("#enterprise_form").animate({height:'740px'}, 200);
		                                                         			
								//$("#confirmation-block").show( 1, function() {																															
						//});
																																
		            // BRENDAN REMOVED RELOAD SO HIDDEN MESSAGE COULD BE DISPLAYED ON PAGE AFTER SUBMISSION
		            // alert("THANK YOU FOR YOUR SUBMISSION.INCIPIO will be following up with you shortly.For questions, email: enterprise@incipio.com");
		            // location.reload();
		        }
	        });
	      }
	                                              
	  });  
	})
	</script>
	
	<div id="enterprise_form_container">
		
		<!-- GRATUITOUS COMMENT CHECKING FOR UPDATE -->
		<form action="form-to-email.php" method="post" name="myemailform" id="myemailform">
	
			<input name="name" type="text" id="name" size="32" placeholder="Name" required>

	    	<input type="text" name="company" id="company" placeholder="Company Name" required>
				
			<input name="email" type="text" id="email" size="32" placeholder="Email Address" required>
				
			<input name="phone" type="text" id="phone" size="32" placeholder="Phone Number" required>
				
			<textarea name="message" cols="45" rows="6" id="message" class="bodytext" placeholder="Enter Message Here" required></textarea>
				
	    	<input type="submit" name="submit" value="Submit"> 
	    		
		</form>
                                                

	  
  </section>
 


<style>@charset "utf-8";
/* CSS Document */
@charset "utf-8";
/* CSS Document */


.main {
    width: 980px;
    margin: 0px auto;
    display: block;
}
@media only screen and (max-width: 990px) {
	.main {
	    width: 90%;
	    margin: 0px auto;
	    display: block;
	}
	img {
		width:100%;
	}
	#incipio_enterprise {
		min-height: 300px!important;
	}
}


section {
	padding: 40px 0;
}
section ul {
	width: 90%;
	margin: 0 auto;
	display: block;   
	position: relative;
    top: 43px;
    padding-bottom: 60px;
}
.titleP { 
	width: 90%;
	display: block;
	margin: 0 auto!important;
}
#enterprise-layout * {
	background-repeat: no-repeat;
	background-size: cover;
}

#incipio_enterprise {
	background-image: url(http://www.incipio.com/images/enterprise/header.jpg);
	background-repeat: no-repeat;
	background-size: cover;
	 min-height: 527px;
	width: 100%;
}


#business_solutions { 
	 min-height: 137px;
	width: 100%;
	background-color: #00AEEF;
}
#business_solutions h2{
	color:white!important;
	font-size: 39px;
	font-weight: 600;
	text-align: center!important;
	padding-top: 9px;
}
#business_solutions p{
	color: white!important;
	font-family: "Roboto",Arial;
	font-weight: 300;
	text-align: center!important;
}









#enterprise_solutions { 
	 min-height: 532px;
	width: 100%;
	background-color: black;
	display: table;
}
#enterprise_solutions h2{
	color:white!important;
	font-size: 39px;
	font-weight: 600;
	text-align: center!important;
	padding-top: 9px;
}
#enterprise_solutions p{
	color: white!important;
	font-family: "Roboto",Arial;
	font-weight: 300; 
	text-align: center!important;
}
#enterprise_solutions li {
	float: left;
	width: 50%;
	min-height: 136px;
	list-style: none; 
}

#enterprise_solutions li p {
	text-align: left;
	color: white!important;
	position: relative;
	top:-10px;
	left: 10px;

}
#enterprise_solutions li h5 {
	text-align: left;
	color:white!important;
	position: relative;
	top:-10px;
	left: 10px;
	font-size: 19px;
}
#enterprise_solutions ul .left{
	float: left;
	width:25%;
}	
#enterprise_solutions ul .left img{
	min-width: 100px;
}
#enterprise_solutions ul .right{
	float: left;
	width:75%;
}


@media only screen and (max-width: 600px) {
	#enterprise_solutions ul .left{
		float: left;
		width:100%;
	}
	#enterprise_solutions ul .left img{
		display: block;
		margin: 0 auto;
	}
	#enterprise_solutions ul .right{
		float: left;
		width:100%;
	}
	#enterprise_solutions li {
		text-align: center!important;
	}
	#enterprise_solutions li h5 {
		text-align: center!important;
		left: 0!important;
		top:0!important;
	}
}

@media only screen and (min-width: 601px) {
	#enterprise_solutions li p {
		text-align: left!important;
	}
}

.cms-page-view .std li {
	color: white!important;
}
.cms-page-view .std li p{
	position: relative;
	left: 10px;
	width: 90%;
}




@media only screen and (max-width: 990px) {
#enterprise_solutions li {
	width: 100%!important;
}

#enterprise_solutions li img{
	width:100px!important;
	}
}









#enterprise_lifestyle {
	background-image: url(http://www.incipio.com/images/enterprise/life.jpg);
	background-repeat: no-repeat;
	background-size: cover;
	 min-height: 389px;
	width: 100%;
}

 

#enterprise_lifestyle2 {
	background-image: url(http://www.incipio.com/images/enterprise/flexin.jpg);
	background-repeat: no-repeat;
	background-size: cover;
	 min-height: 389px;
	width: 100%;
}

 
#solutions_focused { 
	 min-height: 510px;
	width: 100%;
	background: #f6f8f9; /* Old browsers */
	background: -moz-linear-gradient(top, #f6f8f9 0%, #d4d6db 100%, #f5f7f9 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f6f8f9), color-stop(100%,#d4d6db), color-stop(100%,#f5f7f9)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top, #f6f8f9 0%,#d4d6db 100%,#f5f7f9 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top, #f6f8f9 0%,#d4d6db 100%,#f5f7f9 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top, #f6f8f9 0%,#d4d6db 100%,#f5f7f9 100%); /* IE10+ */
	background: linear-gradient(to bottom, #f6f8f9 0%,#d4d6db 100%,#f5f7f9 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f6f8f9', endColorstr='#f5f7f9',GradientType=0 ); /* IE6-9 */
	display: table;
	padding-bottom: 100px;
}
#solutions_focused h2{
	color:black!important;
	font-size: 39px;
	font-weight: 600;
	text-align: center!important;
	padding-top: 9px;
}
#solutions_focused p{
	color: black!important;
	font-family: "Roboto",Arial;
	font-weight: 300;
	text-align: center!important;
}
#solutions_focused li {
	float: left;
	width: 14.285%;
	min-height: 120px;
	list-style: none;
	margin-bottom: 20px;
}
#solutions_focused li img {
	width: 100%;
	max-width: 100px;
	display: block;
	margin: 0 auto;
}

@media only screen and (max-width: 600px) {
	 #solutions_focused li {
		float: left;
		width: 33.33%;
	}
}


















#enterprise_warehouse {
	background-image: url(http://www.incipio.com/images/enterprise/box.jpg);
	background-repeat: no-repeat;
	background-size: cover;
	 min-height: 484px;
	width: 100%;
}

#enterprise_form { 
	 min-height: 436px;
	width: 100%;
	background-color: black;
}

#enterprise_form h2{
	color:white!important;
	font-size: 39px;
	font-weight: 600;
	text-align: center!important;
	padding-top: 9px;
}
#enterprise_form p{
	color: white!important;
	font-family: "Roboto",Arial;
	font-weight: 300;
	text-align: center!important;
}
#enterprise_form form {	
	text-align: center;
}
#enterprise_form form input[type="input"] {
    display: block;
    margin: 0 auto; 
    width: 80%;
}
#enterprise_form textarea {
   display: block;
    margin: 0 auto; 
    width: 80%;
}
#enterprise_form form input[type="submit"] {
    display: block;
    margin: 0px auto;
    height: 34px;
    width: 80%;
    margin-top: 20px;
}

input[type="tel"], input[type="text"] {
    height: 30px;
    padding: 0px 8px;
    width: 80%;
    margin-bottom: 20px;
}



#technology_left {
	width: 400px;
	margin-top: 65px;
	margin-left: 170px;
	float: left;
}
#technology_right {
	margin-top: 65px;
	float: right;
	margin-right: 65px;
}
#solutions_header {
	text-align: center;
}
#solutions_p1 {
	text-align: center;
}




#commercial {
	width: 350px;
}
#technology_header {
	text-align: center;
}
#technology_p1 {
	text-align: center;
}
#partner {
	text-align: center;
}
#partner_p {
	text-align: center;
}
#partner_contact {
	text-align: center;
}
#commercial {
	margin-top: 0px;
}
#education {
}







#finance {
	width: 350px;
}

#education {
	width: 350px;
	margin-top: 35px;
}
#finance {
	margin-top: 30px;
}
#government {
	margin-top: 0px;
}
#healthcare {
	margin-top: 35px;
}
#retail {
	margin-top: 50px;
}
#partner_contact {
	margin-top: 50px;
}

</style>