   <style>
   @media only screen and (min-width: 771px) {
      .col-main {
          padding-top: 79px !important;
      }
    }
    .cms-page-view .std h2, .cms-no-route .std h2 {
       color: #777!important;
    }
    </style>

    <!-- HOMEPAGE + SLIDER ADDITION -->
    <script src="https://www.incipio.com/nivo/jquery.nivo.slider.js"></script>
  

    <!-- HOME PAGE STYLES ONLY -->          
	  <link href="https://www.incipio.com/skin/frontend/rwd/default/css/home_page.css" rel="stylesheet" type="text/css">
      

    <!-- pop up dialog NEWSLETTER -->  
    <script src="skin/frontend/rwd/default/js/jquery.lightbox_me.js" type="text/javascript" charset="utf-8"></script> 
    <script src="skin/frontend/rwd/default/js/jquery.cookie.js" type="text/javascript" charset="utf-8"></script> 

	<!--

    <script type="text/javascript" charset="utf-8"> 
     jQuery(document).ready(function () {
       if (!jQuery.cookie('popUp'))
          { 

            jQuery(function() {
                function launch() {
                     jQuery('#sign_up').lightbox_me({centered: true, onLoad: function() { jQuery('#sign_up').find('input:first').focus()}});
                } 
                jQuery(document).ready(function() {
                      jQuery("#sign_up").lightbox_me({centered: true, preventScroll: true, onLoad: function() {
                      jQuery("#sign_up").find("input:first").focus();
                  }}); 
                }); 
            });
            jQuery.cookie('popUp', "1", {expires: 30});
          }
     });
 
    </script>

    <div id="sign_up" style="display:none;"> 
       <input type="email"><input type="submit" value="submit">
    </div>
     
	-->




	  <!-- INITIALIZE SLIDER -->     
 	  <script type="text/javascript" src="https://www.incipio.com/nivo/jquery.nivo.slider.js"></script>
      <script type="text/javascript">
      	jQuery(window).load(function() {
          jQuery('#slider').nivoSlider();
        });
    </script>
    <!-- END INITIALIZE SLIDER -->
    	
    	 
      <!-- ###################### --> 
      <!-- BEGIN SLIDER CONTAINER -->  
      <!-- ###################### -->  

      <div class="slider-wrapper theme-default">
       	<div id="slider" class="nivoSlider">
       		
       		<!-- SLIDE -->
          <a href="http://dev.incipio.com/lookbooks/holiday-2014-lookbook"> 
              <img class="slider_banner" src="http://www.incipio.com/images/homepage/desktop/winter-lookbook-banner.jpg" data-thumb="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/phone/winter-lookbook-banner.jpg" alt="" data-transition="fade" />
          </a>   
          
          
         	<!-- SLIDE -->
         	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-cases.html">
         		<img class="slider_banner" src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/desktop/winter-iphone-6-banner2.jpg" data-thumb="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/phone/winter-iphone-6-banner2.jpg" alt="" data-transition="fade" />
            </a>
				
       		<!-- SLIDE -->
        	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-plus-cases.html"> 
          		<img class="slider_banner" src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/desktop/winter-iphone-6-plus-banner2.jpg" data-thumb="https://www.incipio.com/images/homepage/phone/winter-iphone-6-plus-banner2.jpg" alt="" data-transition="fade" />
          </a> 
          
           <!-- SLIDE -->
          <a href="http://dev.incipio.com/cases/ipad-cases/ipad-air-2-cases-and-covers.html "> 
              <img class="slider_banner" src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/desktop/winter-ipad-air-2-banner2.jpg" data-thumb="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/phone/winter-ipad-air-2-banner2.jpg" alt="" data-transition="fade" />
          </a>  
               
        </div>
      </div>
 	  <!-- END SLIDER CONTAINER --> 			
      
 
      <!-- ####################### -->  
      <!-- BEGIN FEATURED PRODUCTS -->
      <!-- ####################### --> 
       
      <section id="featured">
      	<div class="container grid4">
        	<h2><span>Featured Items</span></h2>
        	
        	<div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-cases/rival-co-molded-transparent-textured-case-iphone-6.html">
          		<img src="http://www.incipio.com/images/homepage/iPhone6-Rival-BLK.jpg" alt="Incipio Rival Co-Molded Transparent Textured Case for iPhone 6" /> 
            	<h4>iPhone 6 Rival</h4>
            </a>
          </div>
                
          <div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-cases/ngp-flexible-impact-resistant-case-iphone-6.html">
          		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6_NGPFrost.jpg" alt="Incipio NGP Flexible Impact-Resistant Case for iPhone 6" /> 
            	<h4>iPhone 6 NGP</h4>
            </a>
          </div>
          
          <div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-cases/stowaway-credit-card-case-with-integrated-stand-iphone-6.html">
          		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6_Stowaway.jpg" alt="Incipio STOWAWAY Credit Card Case with Integrated Stand" /> 
            	<h4>iPhone 6 STOWAWAY</h4>
            </a>
          </div>
          
          <div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-cases/edge-chrome-slider-case-with-chrome-finish-iphone-6.html">
          		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6_EdgeChrome.jpg" alt="Incipio EDGE CHROME Slider Case with Chrome Finish for iPhone 6" /> 
            	<h4>iPhone 6 EDGE CHROME</h4>
            </a>
          </div>
                
          <div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-plus-cases/dualpro-hard-shell-case-with-impact-absorbing-core-iphone-6-plus.html">
          		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6Plus_DualPro.jpg" alt="Incipio DualPro Hard Shell Case with Impact Absorbing Core for iPhone 6 Plus" /> 
            	<h4>iPhone 6 Plus DualPro</h4>
            </a>
          </div>
          
          <div class="col featuredItem">
          	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-plus-cases/feather-shine-ultra-thin-snap-on-case-with-brushed-aluminum-finish-iphone-6-plus.html">
          		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6Plus_FeatherShine.jpg" alt="Incipio feather SHINE Ultra Thin Snap-On Case with Brushed Aluminum Finish for iPhone 6 Plus" /> 
            	<h4>iPhone 6 Plus feather SHINE</h4>
            </a>
          </div>
          
          <div class="col featuredItem straggler">
           	<a href="http://dev.incipio.com/cases/iphone-cases/iphone-6-plus-cases/highland-ultra-thin-folio-case-iphone-6-plus.html">
           		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_iPh6Plus_Highland.jpg" alt="Incipio Highland Ultra Thin Premium Folio with Brushed Aluminum Style Finish for iPhone 6 Plus"/> 
            	<h4>iPhone 6 Plus Highland</h4>
            </a>
          </div>
		  
          <div class="col featuredItem straggler">
           	<a href="http://dev.incipio.com/chargers/offgrid-portable-backup-batteries/offgrid-trade-portable-backup-battery-4000mah.html">
           		<img src="https://d2zmgde9txxwg2.cloudfront.net/images/homepage/2014_12_01_Featured_RED4K_BackupBattery.jpg" alt="offGRID Portable Backup Battery 4000mAh" /> 
            	<h4>4000 mAh Backup Battery Bank</h4>
            </a>
          </div>
          
        </div>
      </section>
      <!-- END FEATURED PRODUCTS -->
      
      
      <!-- ################ -->  
      <!-- BEGIN WHAT'S NEW -->
      <!-- ################ -->
      
      <section id="new">
        <div class="container">
          <h2><span>What&rsquo;s new</span></h2>
           
            <!-- LEFT COLUMN -->       
            <a href="http://dev.incipio.com/cases/tablet-cases/microsoft-surface-cases-sleeves/microsoft-surface-pro-3-cases-sleeves-covers/ord-protective-padded-sleeve.html">     
              <div class="left" id="newMain">
                <div class="newTitle">
                  <h4>Microsoft Surface Pro 3 ORD Sleeve</h4>
                </div>
              </div> 
            </a>
            <!-- END LEFT COLUMN -->
          
            <!-- START RIGHT COLUMN -->      
            <div class="right">
            
            <!-- RIGHT - TOP -->
            <a href="http://dev.incipio.com/keyboards.html">     
              <div class="newSide top">
                <div class="newTitle">
                  <h4>iPad Air STENO Bluetooth Keyboard Folio</h4>
                </div>
              </div> 
            </a> 
            
            <!-- RIGHT - BOTTOM -->   
               
              <div class="newSide bottom">

                <p class="overlayText">STAY IN THE KNOW.</p>

               
                <div class="newTitle">
                  <h4>SIGN UP HERE TO GET THE LATEST UPDATES</h4>
                </div>

              </div> 
             

            <form id="mc-embedded-subscribe-form" class="validate homepageNewForm" 
              action="https://incipio.us2.list-manage.com/subscribe/post?u=69b6f0214b67470e06547aeb0&amp;id=103aa41e1f" method="post" 
              name="mc-embedded-subscribe-form" target="_blank">
      
              <input id="mce-EMAIL" class="email"  title="SIGN UP FOR OUR NEWSLETTER" 
              type="email" name="EMAIL" /> 
              <input id="mc-embedded-subscribe" class="button"  type="submit" 
              name="subscribe" value="JOIN" />
            </form>
             
          </div>
          <!-- END RIGHT COLUMN -->
     
        </div>
      </section>
	  
     
 
<div class="container">

  <figure> 
    <video  poster="https://www.incipio.com/images/homepage/d.jpg" autoplay loop>
      <source src="http://www.incipio.com/media/videos/hv.mp4" type="video/mp4">
      <source src="http://www.incipio.com/media/videos/hv.webm" type="video/webm">
      <source src="http://www.incipio.com/media/videos/hv.ogg" type="video/ogg">
    </video> 
  </figure>

</div> 
<style>


@media screen and (max-width: 600px) {
  figure {
    position: relative!important;
    display: table!important;
    height: auto!important;
  }
  video {
      position: relative!important; 
  }
}

figure, video {
  width:100%!important;
}


figure {
  position: relative;
  height: 300px;
  overflow: hidden;
}
video {
    position: absolute;
    clip: rect(0px, 980px, 300px, 0px);
}
#shipping {
  margin-top: 15px;
}
}

li{
  list-style: none!important;
}


</style>

        
      
      <!-- ################### -->          
      <!-- BEGIN POPULAR ITEMS -->
      <!-- ################### -->
      
      <section id="popular">
        <div class="container grid4">
        <h2><span>Popular Products</span></h2>
          <ul>
          <?php
          
            $_popularProducts = Mage::getModel('catalog/category')
            ->load(307)
            ->getProductCollection();
          
            $_popProducts = array();
            foreach($_popularProducts->getAllIds() as $_productId) {
          
              $_product = Mage::getModel('catalog/product')->load($_productId);
            
              $_popProducts[$_product->getName()] = array(  
                'id' => $_productId,
                'url' => $_product->getProductUrl(),
                'name' => $_product->getName(),
                'short-desc' => $_product->getShortDescription(),
                'price' => $_product->getPrice(),
                'device_type' => $_product->getDeviceType()
              );
            }
            $_popTrim = array_slice($_popProducts,0,12,true);
                      
            foreach($_popTrim as $_name => $_product):
          ?>
          
          <li class="popItem col" style="list-style: none!important;">
            <a href="<?php echo $_product['url'] ?>">
              <img src="<?php echo $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($_product['id']), 'image')->resize(168, 229) ?>" width="168" height="229" alt="<?php echo $_name ?>" />
              <h4 class="popItemTitle"style="margin:0;"><?php echo $_product['name']; ?> </h4>
            </a>
          <!--<p class="popItemDescription"><?php echo $_product['short-desc']; ?></p>-->
          <p class="popItemDescription" style="margin:0;"><?php echo $_product['device_type']; ?></p>
            <p class="popItemPrice" style="margin:0;"><?php echo "$" . round($_product['price'], 2); ?></p>
        </li>
          
        <?php endforeach; ?> 
                   
          </ul>
        </div>
      </section>
      <!-- END POPULAR ITEMS -->
      
      <link rel="stylesheet" href="https://www.incipio.com/nivo/themes/default/default.css" type="text/css" media="screen" /> 
      <link rel="stylesheet" href="https://www.incipio.com/nivo/themes/bar/bar.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="https://www.incipio.com/nivo/nivo-slider.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="https://www.incipio.com/nivo/demo/style.css" type="text/css" media="screen" />

	  <!-- SLIDER IMAGE PATH SWAP -->
      <script>	
    			jQuery(document).ready(function() {
    			    function checkWidth() {
    			        var windowSize = jQuery(window).width();
    			
    			        if (windowSize >= 771) {
    			            replaceImagePaths("desktop");
    			        }
    			        else if (windowSize < 771 && windowSize > 500) {
    			            replaceImagePaths("tablet");
    			        }
    			        else {
    			            replaceImagePaths("phone");
    			        }
    			    }
    					function replaceImagePaths(resolution) {
       	
        			jQuery('img.slider_banner').each(function(){
            		var imagePath = jQuery(this).attr('src');
            		jQuery(this).attr('src', imagePath.replace(/phone|tablet|desktop/, resolution));
       					});
       				}	
    			    // ON LOAD
    			    checkWidth();
    			    
    			    // RESIZE
    			    jQuery(window).resize(checkWidth);
    			});
    			
    	</script>
   