    <!-- HOMEPAGE + SLIDER ADDITION -->
    <script src="nivo/jquery.nivo.slider.js"></script>
    <link rel="stylesheet" href="nivo/themes/default/default.css" type="text/css" media="screen" /> 
    <link rel="stylesheet" href="nivo/themes/bar/bar.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="nivo/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="nivo/demo/style.css" type="text/css" media="screen" />


    <style>
      @media all and (min-width: 771px) {
        .col-main {
            padding-top: 79px !important;
        }

      }
    </style>

    <!-- HOME PAGE STYLES ONLY -->          
	  <link href="skin/frontend/rwd/default/css/home_page.css" rel="stylesheet" type="text/css">
      

    <!-- pop up dialog NEWSLETTER -->  
    <script src="skin/frontend/rwd/default/js/jquery.lightbox_me.js" type="text/javascript" charset="utf-8"></script> 
    <script src="skin/frontend/rwd/default/js/jquery.cookie.js" type="text/javascript" charset="utf-8"></script> 
 




	  <!-- INITIALIZE SLIDER -->     
 	  <script type="text/javascript" src="nivo/jquery.nivo.slider.js"></script>
      <script type="text/javascript">
      	jQuery(window).load(function() {
          jQuery('#slider').nivoSlider();
        });
    </script>
    <!-- END INITIALIZE SLIDER -->
    	
    	 
      
      <!-- ###################### --> 
      <!-- BEGIN SLIDER CONTAINER -->  
      <!-- ###################### -->  
       
      <div class="slider-wrapper theme-default">
       	<div id="slider" class="nivoSlider">  
       		   
       		<!-- SLIDE 1 -->
        	<a href="#"> 
          	<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" alt="" data-transition="fade" />
          </a>  
        	
        	<!-- SLIDE 2 -->      
         	<a href="#"> 
            <img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" alt="" data-transition="fade" />
          </a>  
          
          <!-- SLIDE 3 -->
          <a href="#"> 
            <img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/kateSpadeSlide1.jpg" alt="" data-transition="fade" />
          </a>  
          
        </div>
      </div>
 	  <!-- END SLIDER CONTAINER -->
 		<!-- END POPULAR ITEMS -->
<div class="kateSpadePage">
  <div class="container">
 
        <img src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/ksSpade.png" id="spadeImg">

         <div id="nav-trigger">
            <span>Menu</span>
        </div>

        <nav id="nav-main">
            <ul>
                <li><a href="">new arrivals</a></li>
                <li><a href="">phone</a></li>
                <li><a href="">tablet</a></li>
                <li><a href="">laptop</a></li>
                <li><a href="">chargers</a></li>
            </ul>
        </nav>

        <nav id="nav-mobile"></nav>
  

    <div id="imageGrid" style="clear: both">
        <div class="half">
          <a href=""><img src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/ks_shop_iphone.jpg"></a>
          <h2 style="margin: 0 auto;">SHOP IPHONE</h2>
        </div>
        <div class="half">
            <a href=""><img src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/ks_shop_chargers.jpg"></a>
            <a href=""><img src="http://d2zmgde9txxwg2.cloudfront.net/images/kateSpade/ks_shop_ipad.jpg"></a>
        </div>
      </div>
    </div>

    <div class="container grid4">
     
      <h2><span>Featured Items</span></h2>
     
      <li class="popItem col">
          <a href="http://www.incipio.com/iphone-5s-atlas-id-ultra-rugged-waterproof-case.html">
            <img src="http://d2zmgde9txxwg2.cloudfront.net/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/n/incipio-iphone-5-5s-atlas-id-case-black-ab_1.jpg" alt="ATLAS ID™">
            <h4 class="popItemTitle">ATLAS ID™ </h4>
          </a>
        <!--<p class="popItemDescription">Ultra Rugged Waterproof Case</p>-->
        <p class="popItemDescription">for iPhone 5/5s</p>
          <p class="popItemPrice">$89.99</p>
      </li>

      <li class="popItem col">
          <a href="http://www.incipio.com/iphone-5s-atlas-id-ultra-rugged-waterproof-case.html">
            <img src="http://d2zmgde9txxwg2.cloudfront.net/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/n/incipio-iphone-5-5s-atlas-id-case-black-ab_1.jpg" alt="ATLAS ID™">
            <h4 class="popItemTitle">ATLAS ID™ </h4>
          </a>
        <!--<p class="popItemDescription">Ultra Rugged Waterproof Case</p>-->
        <p class="popItemDescription">for iPhone 5/5s</p>
          <p class="popItemPrice">$89.99</p>
      </li>

      <li class="popItem col">
          <a href="http://www.incipio.com/iphone-5s-atlas-id-ultra-rugged-waterproof-case.html">
            <img src="http://d2zmgde9txxwg2.cloudfront.net/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/n/incipio-iphone-5-5s-atlas-id-case-black-ab_1.jpg" alt="ATLAS ID™">
            <h4 class="popItemTitle">ATLAS ID™ </h4>
          </a>
        <!--<p class="popItemDescription">Ultra Rugged Waterproof Case</p>-->
        <p class="popItemDescription">for iPhone 5/5s</p>
          <p class="popItemPrice">$89.99</p>
      </li>

      <li class="popItem col">
          <a href="http://www.incipio.com/iphone-5s-atlas-id-ultra-rugged-waterproof-case.html">
            <img src="http://d2zmgde9txxwg2.cloudfront.net/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/i/n/incipio-iphone-5-5s-atlas-id-case-black-ab_1.jpg" alt="ATLAS ID™" >
            <h4 class="popItemTitle">ATLAS ID™ </h4>
          </a>
        <!--<p class="popItemDescription">Ultra Rugged Waterproof Case</p>-->
        <p class="popItemDescription">for iPhone 5/5s</p>
          <p class="popItemPrice">$89.99</p>
      </li>

    </div>
  </div>
</div>










<!-- css -->
<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,700,400italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'> 
    
<script type="text/javascript" src="http://www.incipio.com/skin/frontend/rwd/default/js/kateSpade/modernizr.custom.js"></script> 
<script>
    jQuery(document).ready(function(){
        jQuery("#nav-mobile").html(jQuery("#nav-main").html());
        jQuery("#nav-trigger span").click(function(){
            if (jQuery("nav#nav-mobile ul").hasClass("expanded")) {
                jQuery("nav#nav-mobile ul.expanded").removeClass("expanded").slideUp(250);
                jQuery(this).removeClass("open");
            } else {
                jQuery("nav#nav-mobile ul").addClass("expanded").slideDown(250);
                jQuery(this).addClass("open");
            }
        });
    });
</script>