<script type="text/javascript" src="/js-ecom/jquery.maphilight.js"></script>
<script type="text/javascript">
	jQuery.noConflict();	
    jQuery(document).ready(function(){
        jQuery('.map').maphilight();
    });
</script>
				
<div id="content">
<section class="collection">
<ul id="the_collection">
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_01.jpg" title="" usemap="#Map" border="0" /> <map id="Map" name="Map"> 
<area shape="rect" coords="723,215,982,483" href="http://www.incipio.com/cases/ipad-cases/new-ipad-cases/ipad-retina-new-ipad-ngp-semi-rigid-soft-shell-case.html" title="NGP iPad Retina Display Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' alt='Link'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_02.jpg" title="" usemap="#Map2" border="0" /> <map id="Map2" name="Map2"> 
<area shape="rect" coords="72,74,237,205" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-edge-cf-case.html" title="EDGE CF iPhone 5 Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="248,195,355,305" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-printed-feather-shine.html" title="Printed feather SHINE iPhone 5 Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="866,75,1191,370" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-edge-cf-case.html" title="EDGE CF iPhone 5 Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map> </li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_03.jpg" title="" usemap="#Map3" border="0" /> <map id="Map3" name="Map3"> 
<area shape="rect" coords="124,346,304,580" href="http://www.incipio.com/cases/power-solutions/power-solutions-for-apple/iphone-power-solutions.html" title="iPhone 5 Lightning Charger" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="582,298,752,492" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-printed-feather-shine.html" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' title='iPhone 5 Printed feather Shine'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_04.jpg" title="" usemap="#Map4" border="0" /> <map id="Map4" name="Map4"> 
<area shape="rect" coords="516,11,775,190" href="http://www.incipio.com/cases/ipad-cases/new-ipad-cases/ipad-retina-new-ipad-flagship-folio-brushed-aluminum-hard-shell-case.html" title="Flagship Folio iPad Retina Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="542,403,690,576" href="http://www.incipio.com/cases/smartphone-cases/samsung-smartphone-cases-accessories/samsung-galaxy-s3-cases/samsung-galaxy-s-3-offgrid-case.html" title="Samsung Galaxy SIII offGRID Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_05.jpg" title="" usemap="#Map5" border="0" /> <map id="Map5" name="Map5"> 
<area shape="rect" coords="589,26,813,197" href="http://www.incipio.com/cases/smartphone-cases/samsung-smartphone-cases-accessories/samsung-galaxy-s3-cases/samsung-galaxy-s-3-offgrid-case.html" title="Samsung Galaxy SIII offGRID Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_06.jpg" title="" usemap="#Map6" border="0" /> <map id="Map6" name="Map6"> 
<area shape="rect" coords="158,93,377,268" href="http://www.incipio.com/cases/smartphone-cases/blackberry-cases/blackberry-z10-cases/blackberry-z10-ovrmld-case-with-holster.html" title="[OVRMLD] Blackberry Z10 Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="855,148,1106,386" href="http://www.incipio.com/cases/smartphone-cases/blackberry-cases/blackberry-z10-cases/blackberry-z10-ovrmld-case-with-holster.html" title="[OVRMLD] Blackberry Z10 Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_07.jpg" title="" /></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_08.jpg" title="" usemap="#Map7" border="0" /> <map id="Map7" name="Map7"> 
<area shape="rect" coords="601,212,861,553" href="http://www.incipio.com/cases/smartphone-cases/blackberry-cases/blackberry-z10-cases/blackberry-z10-feather-case.html" title="Blackberry Z10 feather Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_09.jpg" usemap="#Map14" class="map" title="" border="0" />
  <map name="Map14">
    <area shape="rect" coords="304,268,564,441" href="http://www.incipio.com/cases/smartphone-cases/htc-smartphone-cases/htc-one-cases/htc-one-dualpro-shine-case.html" target="_blank" title="HTC One DualPro SHINE Case" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
    <area shape="rect" coords="471,116,671,249" href="http://www.incipio.com/cases/smartphone-cases/htc-smartphone-cases/htc-one-cases/htc-one-dualpro-cf-case.html" target="_blank" title="HTC One DualPro CF Case" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
  </map>
</li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_10.jpg" title="" usemap="#Map9" border="0" /> <map id="Map9" name="Map9"> 
<area shape="rect" coords="57,203,318,540" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-six-patterned-cut-out-case.html" title="iPhone 5 Six Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
<area shape="rect" coords="763,339,930,528" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-six-patterned-cut-out-case.html" title="iPhone 5 Six Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
<area shape="rect" coords="344,111,593,436" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-six-patterned-cut-out-case.html" target="_blank" title="iPhone 5 Six Case" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
 
<area shape="rect" coords="763,339,930,528" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-six-patterned-cut-out-case.html" title="iPhone 5 Six Case" target="_blank" alt="iPhone 5 Six Case" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_11.jpg" title="" usemap="#Map10" border="0" /> <map id="Map10" name="Map10"> 
<area shape="rect" coords="36,154,352,460" href="http://www.incipio.com/cases/ipod-cases/ipod-touch-5g-cases/ipod-touch-5g-hive-response-case.html" title="iPod Touch 5G Hive Response Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="579,231,791,455" href="http://www.incipio.com/cases/ipod-cases/ipod-touch-5g-cases/ipod-touch-5g-hive-response-case.html" title="iPod Touch 5G Hive Response Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_12.jpg" title="" usemap="#Map11" border="0" /> <map id="Map11" name="Map11"> 
<area shape="rect" coords="158,205,303,377" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-atlas-waterproof-ultra-rugged-case.html" title="ATLAS iPhone 5 Waterproof Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="816,44,1169,551" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-atlas-waterproof-ultra-rugged-case.html" title="ATLAS iPhone 5 Waterproof Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_13.jpg" title="" usemap="#Map12" border="0" /> <map id="Map12" name="Map12"> 
<area shape="rect" coords="146,247,317,359" href="http://www.incipio.com/cases/amazon-kindle-carrying-cases/amazon-kindle-paperwhite-cases/amazon-kindle-paperwhite-kaddy-case.html" title="Kindle Paperwhite Kaddy Folio" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="285,374,378,433" href="http://www.incipio.com/cases/ipod-cases/ipod-touch-5g-cases/ipod-touch-5g-hive-response-case.html" title="iPod Touch 5G Hive Response Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="409,281,502,414" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-atlas-waterproof-ultra-rugged-case.html" title="ATLAS iPhone 5 Waterproof Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="725,18,1183,481" href="http://www.incipio.com/cases/amazon-kindle-carrying-cases/amazon-kindle-paperwhite-cases/amazon-kindle-paperwhite-kaddy-case.html" title="Kindle Paperwhite Kaddy Folio" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img class="map" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Spring13/Image_14.jpg" title="" usemap="#Map13" border="0" /> <map id="Map13" name="Map13"> 
<area shape="rect" coords="322,169,541,460" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-atlas-waterproof-ultra-rugged-case.html" title="ATLAS iPhone 5 Waterproof Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 
<area shape="rect" coords="805,128,986,299" href="http://www.incipio.com/cases/iphone-cases/iphone-5-cases/iphone-5-atlas-waterproof-ultra-rugged-case.html" title="ATLAS iPhone 5 Waterproof Case" target="_blank" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}'/>
 </map></li>
<li><img src="http://incipio.com/images/Lookbooks/Spring13/Image_15.jpg" usemap="#Map8" class="map" title="" border="0" />
  
  <div class="wrapperVideoSlide">
  <map name="Map8" id="Map8">
  		
  	<div class="wrapperLookbookVideo" id="videoLookbookSpring13"> 
  		<iframe width="560" height="315" src="http://www.youtube.com/embed/5Rjuw-TVLno?wmode=opaque&hd=1&rel=0&autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>
  	</div>	<!-- END WRAPPER LOOKBOOK VIDEO -->
  	
    <area shape="rect" coords="770,296,849,322" href="http://incipio.com/store" target="_blank" alt="Incipio.com" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="850,296,908,322" href="https://www.facebook.com/incipio" target="_blank" alt="Incipio on Facebook" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="909,296,982,322" href="https://twitter.com/myIncipio" target="_blank" alt="Incipio on Twitter" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="983,296,1051,322" href="http://instagram.com/incipio" target="_blank" alt="Incipio on Instagram" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="928,389,1026,404" href="mailto:PR@incipio.com" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="928,405,1044,421" href="mailto:sales@incipio.com" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
    <area shape="rect" coords="813,461,1003,479" href="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/PDF/2013-Spring-Lookbook.pdf" alt="Incipio Spring 2013 Lookbook" data-maphilight='{"strokeColor":"000000","fillColor":"ffffff","fillOpacity":0.0}' />
  </map>
  </div> <!-- END WRAPPER VIDEO SLIDE -->
</li>

</ul>

	<nav class="collections">
	  <div id="prev">&nbsp;</div>
							<div id="next">&nbsp;</div>	
	</nav>	
</section>
<link rel="stylesheet" type="text/css" media="all" href="/styles/Lookbook.css" />
<link rel="stylesheet" type="text/css" media="all" href="/styles/lookbookLayout.css" />
<link rel="stylesheet" type="text/css" media="all" href="/styles/lookbookSlide.css" />
<link rel="stylesheet" type="text/css" media="all" href="/styles/responsiveslides.css" />

<script type="text/javascript" src="/js-ecom/jquery.easing.js"></script>
<script type="text/javascript" src="/js-ecom/jquery.cycle.js"></script>
<script type="text/javascript" src="/js-ecom/qp.js"></script>
<script type="text/javascript">
qp.collection();
</script>
</div>