<script src="//www.incipio.com/nivo/jquery.nivo.slider.js"></script>
<link href="skin/frontend/rwd/default/css/home_page.css" rel="stylesheet" type="text/css">


<!-- INITIALIZE SLIDER -->     
<script type="text/javascript" src="nivo/jquery.nivo.slider.js"></script>
	<script type="text/javascript">
	jQuery(function(){
	 jQuery('#slider').nivoSlider({
    // Your settings here
    manualAdvance:true
});
  });
</script>
<!-- END INITIALIZE SLIDER -->








<style>

#shipping {
    margin-top: -21px!important;
    display: none;
}
@media only screen and (max-width: 771px) {
  .col1-layout .col-main {
    min-height: 0!important;
  }
  .nivoSlider {
    position: relative;
    width: 100%; 
  }
   .theme-default .nivoSlider { 
      margin-bottom: -12px;
  }
  .container, .main {
      width: 100%; 
  }
 footer .container,footer .main {
      width: 90%; 
  }
}
@media only screen and (min-width: 771px) {
  .lookBook {
    	margin-top: -27px;
    }
    .nivoSlider {
      position: relative;
      width: 90%!important;
      height: auto;
      overflow: hidden;
      margin: 85px auto;
  }
  .nivo-controlNav { 
      display: block!important;
      position: relative;
      top: -30px;
  }
}

@media only screen and (min-width: 990px) {
  .lookBook {
      margin-top: -27px;
    }
    .nivoSlider {
      position: relative;
      width: 980px!important;
      height: auto;
      overflow: hidden;
      margin: 85px auto;
  }
}

</style>
	 
  
  <!-- ###################### --> 
  <!-- BEGIN SLIDER CONTAINER -->  
  <!-- ###################### -->  
   
  <div class="slider-wrapper theme-default lookBook">
   	<div id="slider" class="nivoSlider">  
   		   
   		<!-- SLIDE 1 -->
      <img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook.jpg" alt="" data-transition="fade" />
    	<!-- SLIDE 2 -->     
  		<a href="http://www.incipio.com/chargers/offgrid-backup-battery-cases/offgrid-print-backup-battery-2000-mah-case-for-iphone-5.html "><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook2.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook2.jpg" alt="" data-transition="fade" /></a>
 

    	<!-- SLIDE 3 -->     
  		<a href="http://www.incipio.com/cases/iphone-cases/iphone-5s-cases/iphone-5s-atlas-id-ultra-rugged-waterproof-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook3.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook3.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 4 -->     
  		<a href="http://www.incipio.com/cases/samsung-smartphone-cases/samsung-galaxy-s5/octane-comolded-case-samsung-galaxy-s5.html "><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook4.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook4.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 5 -->     
  		<a href="http://www.incipio.com/cases/iphone-cases/iphone-5c-cases/watson-folio-wallet-for-iphone-5c.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook5.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook5.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 6 -->     
  		<a href="http://www.incipio.com/cases/macbook-cases/macbook-pro-13in-cases/macbook-pro-13in-ronin-sleeve.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook6.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook6.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 7 -->     
  		<a href="http://www.incipio.com/cases/ipad-cases/ipad-air-cases-and-covers/lgnd-ipad-air-hard-shell-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook7.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook7.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 8 -->     
  		<a href="http://www.incipio.com/custom-cases/iphone-5-5s-custom-cases/limited-edition-paisley-etched-feather-reg-shine-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook8.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook8.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 9 -->     
  		<a href="http://www.incipio.com/cases/smartphone-cases/lg-smartphone-cases/lg-g3-cases/lg-g3-ngp-ultra-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook9v1.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook9.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 10 -->     
  		<a href="http://www.incipio.com/chargers/offgrid-backup-battery-cases/offgrid-rugged-battery-case-2000mah-for-iphone-5.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook10.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook10.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 11 -->     
  		<a href=" http://www.incipio.com/custom-cases/iphone-5-5s-custom-cases/limited-edition-tribal-etched-feather-reg-shine-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook11.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook11.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 12 -->     
  		<a href="http://www.incipio.com/cases/samsung-smartphone-cases-accessories/samsung-galaxy-s5/phenom-lightweight-case-samsung-galaxy-s5.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook12.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook12.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 13 -->     
  		<a href="http://www.incipio.com/cases/iphone-cases/iphone-5s-cases/iphone-5s-performance-armband.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook13.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook13.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 14 -->     
  		<a href="http://www.incipio.com/cases/iphone-cases/iphone-5c-cases/ngp-case-for-iphone-5c.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook14.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook14.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 15 -->     
  		<a href="http://www.incipio.com/cases/samsung-smartphone-cases/samsung-galaxy-s5/octane-comolded-case-samsung-galaxy-s5.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook15.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook15.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 16 -->     
  		<a href="http://www.incipio.com/cases/ipad-cases/ipad-air-cases-and-covers/invert-universal-folio-10in.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook16.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook16.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 17 -->     
  		<a href="http://www.incipio.com/cases/ipad-cases/ipad-mini-with-retina-display-cases-and-covers/ipad-mini-with-retina-display-lgnd-case.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook17.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook17.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 18 -->     
  		<a href="http://www.incipio.com/cases/ipad-cases/ipad-air-cases-and-covers/capture-dual-layer-case-with-adjustable-handle-for-ipad-air.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook18.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook18.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 19 -->     
  		<a href="http://www.incipio.com/cases/tablet-cases/sony-cases/sony-xperia-z2-tablet-cases/lexington-case-sony-xperia-z2-tablet.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook19.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook19.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 20 -->     
  		<a href="http://www.incipio.com/cases/samsung-smartphone-cases-accessories/samsung-galaxy-s5/highland-folio-samsung-galaxy-s5.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook20.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook20.jpg" alt="" data-transition="fade" /></a>

  		<!-- SLIDE 21 -->     
  		<a href="http://www.incipio.com/cases/iphone-cases/iphone-5s-cases/focal-camera-case-for-iphone-5s.html"><img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook21.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook21.jpg" alt="" data-transition="fade" /> </a>    
    </div>
  </div>
 <!-- END SLIDER CONTAINER -->



      <link rel="stylesheet" href="//www.incipio.com/nivo/themes/default/default.css" type="text/css" media="screen" /> 
      <link rel="stylesheet" href="//www.incipio.com/nivo/themes/bar/bar.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="//www.incipio.com/nivo/nivo-slider.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="//www.incipio.com/nivo/demo/style.css" type="text/css" media="screen" />

