<script src="nivo/jquery.nivo.slider.js"></script>

<link href="skin/frontend/rwd/default/css/home_page.css" rel="stylesheet" type="text/css">


<!-- INITIALIZE SLIDER -->     
<script type="text/javascript" src="nivo/jquery.nivo.slider.js"></script>
	<script type="text/javascript">
	jQuery(function(){
	 jQuery('#slider').nivoSlider({
    // Your settings here
    manualAdvance:true
});
  });
</script>
<!-- END INITIALIZE SLIDER -->








<style>

#shipping {
    margin-top: -21px!important;
    display: none;
}
@media only screen and (max-width: 771px) {
  .col1-layout .col-main {
    min-height: 0!important;
  }
  .nivoSlider {
    position: relative;
    width: 100%; 
  }
   .theme-default .nivoSlider { 
      margin-bottom: -12px;
  }
}
@media only screen and (min-width: 771px) {
  .lookBook {
    	margin-top: -27px;
    }
    .nivoSlider {
      position: relative;
      width: 90%!important;
      height: auto;
      overflow: hidden;
      margin: 85px auto;
  }
}

@media only screen and (min-width: 990px) {
  .lookBook {
      margin-top: -27px;
    }
    .nivoSlider {
      position: relative;
      width: 980px!important;
      height: auto;
      overflow: hidden;
      margin: 85px auto;
  }
}

</style>
	 
  
  <!-- ###################### --> 
  <!-- BEGIN SLIDER CONTAINER -->  
  <!-- ###################### -->  
   
  <div class="slider-wrapper theme-default lookBook">
   	<div id="slider" class="nivoSlider">  
   		   
   		<!-- SLIDE 1 -->
      <img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook.jpg" alt="" data-transition="fade" />
 
    	<!-- SLIDE 2 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook2.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook2.jpg" alt="" data-transition="fade" />

    	<!-- SLIDE 3 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook3.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook3.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 4 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook4.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook4.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 5 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook5.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook5.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 6 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook6.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook6.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 7 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook7.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook7.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 8 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook8.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook8.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 9 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook9.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook9.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 10 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook10.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook10.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 11 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook11.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook11.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 12 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook12.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook12.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 13 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook13.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook13.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 14 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook14.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook14.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 15 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook15.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook15.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 16 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook16.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook16.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 17 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook17.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook17.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 18 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook18.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook18.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 19 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook19.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook19.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 20 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook20.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook20.jpg" alt="" data-transition="fade" />

  		<!-- SLIDE 21 -->     
  		<img class="slider_banner" src="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook21.jpg" data-thumb="http://d2zmgde9txxwg2.cloudfront.net/images/Lookbooks/Summer14/2014_SummerLookbook21.jpg" alt="" data-transition="fade" />     
    </div>
  </div>
 <!-- END SLIDER CONTAINER -->



      <link rel="stylesheet" href="nivo/themes/default/default.css" type="text/css" media="screen" /> 
      <link rel="stylesheet" href="nivo/themes/bar/bar.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="nivo/nivo-slider.css" type="text/css" media="screen" />
      <link rel="stylesheet" href="nivo/demo/style.css" type="text/css" media="screen" />